import type { MapPoint } from "./types";

export type MountainAtlasSubtype =
  | "mountain-fold"
  | "mountain-fault-block"
  | "mountain-volcanic";

export type MountainAtlasEntry = {
  id: string;
  label: string;
  provinceCode: number;
  subtype: MountainAtlasSubtype;
  description: string;
  sourceLabel: string;
  sourceUrl: string;
  image?: string;
};

export type MountainAtlasLayout = {
  point: MapPoint;
  labelOffset: MapPoint;
  labelRotation?: number;
  symbolScale?: number;
};

type MountainAtlasSeed = MountainAtlasEntry & {
  layout: MountainAtlasLayout;
};

type MountainOptions = {
  image?: string;
  labelRotation?: number;
  symbolScale?: number;
};

const MEB_SOURCE_LABEL = "MEB Coğrafya ders materyali";
const MEB_SOURCE_URL =
  "https://orgm.meb.gov.tr/ekpssmebozel/content/magazines/pdf/cografya2.pdf";

const FORMATION_NOTE: Record<MountainAtlasSubtype, string> = {
  "mountain-fold": "Kıvrım dağları grubunda gösterilir.",
  "mountain-fault-block": "Kırık dağ (horst) grubunda gösterilir.",
  "mountain-volcanic": "Volkanik dağlar grubunda gösterilir.",
};

/**
 * turkey-map-react il patikalarıyla kalibre edilmiş doğrudan SVG noktaları.
 * Referans görsel şematik olduğu için ham görsel oranları özellikle Orta ve
 * Doğu Anadolu'da illeri batıya kaydırıyordu. Bu noktalar her dağın temsil
 * edildiği gerçek il/bölge kuşağına oturur.
 */
const MOUNTAIN_ATLAS_POINTS: Record<string, MapPoint> = {
  "akdaglar": { x: 189, y: 523 },
  "aladaglar": { x: 474, y: 473 },
  "allahuekber-daglari": { x: 900, y: 257 },
  "amanos-daglari": { x: 556, y: 562 },
  "aras-daglari": { x: 948, y: 292 },
  "aydin-daglari": { x: 115, y: 449 },
  "barla-dagi": { x: 275, y: 446 },
  "beydaglari": { x: 201, y: 541 },
  "biga-daglari": { x: 75, y: 267 },
  "binboga-daglari": { x: 593, y: 434 },
  "bolkar-daglari": { x: 378, y: 553 },
  "bolu-ilgaz-daglari": { x: 391, y: 249 },
  "bozdaglar": { x: 116, y: 416 },
  "buyuk-agri-dagi": { x: 950, y: 315 },
  "buzul-daglari": { x: 1005, y: 455 },
  "canik-daglari": { x: 604, y: 247 },
  "cimen-daglari": { x: 706, y: 316 },
  "dedegol-geyik-daglari": { x: 298, y: 465 },
  "egrigoz-dagi": { x: 190, y: 355 },
  "elmadag": { x: 355, y: 347 },
  "emirdag": { x: 300, y: 375 },
  "erciyes-dagi": { x: 539, y: 415 },
  "giresun-daglari": { x: 666, y: 251 },
  "golgeli-daglari": { x: 188, y: 489 },
  "guneydogu-toroslar": { x: 740, y: 420 },
  "hakkari-daglari": { x: 957, y: 464 },
  "hasan-dagi": { x: 425, y: 426 },
  "hinzir-dagi": { x: 527, y: 374 },
  "honaz-dagi": { x: 211, y: 451 },
  "ihtiyar-sahap-daglari": { x: 941, y: 422 },
  "karacadag-guneydogu": { x: 770, y: 461 },
  "karacadag-ic-anadolu": { x: 370, y: 503 },
  "karadag": { x: 372, y: 527 },
  "karasu-aras-daglari": { x: 830, y: 306 },
  "karcal-daglari": { x: 850, y: 215 },
  "katrancik-daglari": { x: 224, y: 478 },
  "kaz-daglari": { x: 89, y: 317 },
  "kop-daglari": { x: 761, y: 281 },
  "koroglu-daglari": { x: 323, y: 271 },
  "koru-isik-daglari": { x: 89, y: 224 },
  "kucuk-agri-dagi": { x: 982, y: 321 },
  "kula-volkanlari": { x: 162, y: 408 },
  "kure-daglari": { x: 403, y: 189 },
  "madra-dagi": { x: 140, y: 330 },
  "malatya-daglari": { x: 662, y: 427 },
  "mardin-daglari": { x: 816, y: 480 },
  "melendiz-daglari": { x: 464, y: 439 },
  "mentese-daglari": { x: 120, y: 485 },
  "mescit-daglari": { x: 798, y: 270 },
  "munzur-mercan-daglari": { x: 720, y: 352 },
  "murat-dagi": { x: 208, y: 382 },
  "nemrut-dagi": { x: 863, y: 399 },
  "palandoken-daglari": { x: 824, y: 337 },
  "rize-kackar-daglari": { x: 803, y: 236 },
  "samanli-daglari": { x: 235, y: 235 },
  "sandikli-daglari": { x: 240, y: 405 },
  "sivrihisar-daglari": { x: 315, y: 348 },
  "sultan-daglari": { x: 301, y: 399 },
  "sundiken-daglari": { x: 275, y: 315 },
  "suphan-dagi": { x: 895, y: 378 },
  "tahtali-daglari": { x: 578, y: 417 },
  "tecer-daglari": { x: 637, y: 367 },
  "tendurek-dagi": { x: 925, y: 344 },
  "turkmen-dagi": { x: 229, y: 342 },
  "uludag": { x: 190, y: 302 },
  "yalnizcam-daglari": { x: 900, y: 240 },
  "yildiz-daglari": { x: 104, y: 173 },
  "yunt-dagi": { x: 112, y: 378 },
};

/**
 * Referans görseldeki yüzde konumlarını turkey-map-react'in 1050 × 585
 * koordinat sistemine taşır. Kullanılan dönüşüm:
 * x = 22 + oran × 10,06, y = 144 + oran × 4,43.
 */
const pointFromRatio = (xRatio: number, yRatio: number): MapPoint => ({
  x: Number((22 + xRatio * 10.06).toFixed(1)),
  y: Number((144 + yRatio * 4.43).toFixed(1)),
});

const mountain = (
  id: string,
  label: string,
  provinceCode: number,
  subtype: MountainAtlasSubtype,
  description: string,
  xRatio: number,
  yRatio: number,
  labelOffset: MapPoint,
  options: MountainOptions = {},
): MountainAtlasSeed => ({
  id,
  label,
  provinceCode,
  subtype,
  description: `${description} ${FORMATION_NOTE[subtype]}`,
  sourceLabel: MEB_SOURCE_LABEL,
  sourceUrl: MEB_SOURCE_URL,
  ...(options.image ? { image: options.image } : {}),
  layout: {
    point: MOUNTAIN_ATLAS_POINTS[id] ?? pointFromRatio(xRatio, yRatio),
    labelOffset,
    ...(options.labelRotation === undefined
      ? {}
      : { labelRotation: options.labelRotation }),
    ...(options.symbolScale === undefined
      ? {}
      : { symbolScale: options.symbolScale }),
  },
});

const MOUNTAIN_ATLAS_SEEDS: MountainAtlasSeed[] = [
  mountain(
    "yildiz-daglari",
    "Yıldız Dağları",
    39,
    "mountain-fold",
    "Trakya'nın kuzeyinde, Karadeniz kıyısına yakın uzanan Istranca kütlesidir.",
    7,
    7,
    { x: 0, y: 18 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "koru-isik-daglari",
    "Koru–Işık Dağları",
    59,
    "mountain-fold",
    "Trakya'nın güneybatısındaki dağlık kuşağı temsil eder.",
    4,
    18,
    { x: 4, y: 18 },
    { symbolScale: 0.78 },
  ),
  mountain(
    "biga-daglari",
    "Biga Dağları",
    17,
    "mountain-fold",
    "Biga Yarımadası'nın iç kesimlerindeki dağlık alanı oluşturur.",
    5,
    27,
    { x: 2, y: 18 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "kaz-daglari",
    "Kaz Dağları",
    10,
    "mountain-fault-block",
    "Edremit Körfezi'nin kuzeyinde yükselen faylı dağ kütlesidir.",
    6,
    39,
    { x: 10, y: -19 },
    { symbolScale: 0.86 },
  ),
  mountain(
    "samanli-daglari",
    "Samanlı Dağları",
    41,
    "mountain-fold",
    "İzmit Körfezi'nin güneyinde doğu-batı doğrultusunda uzanır.",
    18,
    27,
    { x: 0, y: -18 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "uludag",
    "Uludağ",
    16,
    "mountain-fault-block",
    "Bursa'nın güneyinde yükselen ve faylanmayla belirginleşen kütledir.",
    12,
    31,
    { x: 31, y: -3 },
    { symbolScale: 0.9 },
  ),
  mountain(
    "kure-daglari",
    "Küre Dağları",
    37,
    "mountain-fold",
    "Batı Karadeniz'de kıyıya paralel uzanan Kuzey Anadolu Dağları bölümüdür.",
    33,
    11,
    { x: 0, y: -18 },
    { symbolScale: 0.9 },
  ),
  mountain(
    "bolu-ilgaz-daglari",
    "Bolu–Ilgaz Dağları",
    18,
    "mountain-fold",
    "Batı Karadeniz'in iç sıralarında Bolu'dan Ilgaz'a uzanan kuşaktır.",
    32,
    21,
    { x: 0, y: -22 },
    { symbolScale: 1.08 },
  ),
  mountain(
    "koroglu-daglari",
    "Köroğlu Dağları",
    14,
    "mountain-fold",
    "Bolu çevresinde Kuzey Anadolu Dağları'nın iç sırasını oluşturur.",
    30,
    29,
    { x: -4, y: -20 },
    { labelRotation: -4, symbolScale: 1.02 },
  ),
  mountain(
    "canik-daglari",
    "Canik Dağları",
    52,
    "mountain-fold",
    "Orta Karadeniz'de kıyıya paralel uzanan, görece alçak sıradır.",
    44,
    21,
    { x: 0, y: -19 },
    { symbolScale: 0.88 },
  ),
  mountain(
    "giresun-daglari",
    "Giresun Dağları",
    28,
    "mountain-fold",
    "Doğu Karadeniz Dağları'nın Giresun gerisindeki bölümüdür.",
    55,
    23,
    { x: -7, y: 22 },
    { symbolScale: 0.9 },
  ),
  mountain(
    "rize-kackar-daglari",
    "Rize–Kaçkar Dağları",
    53,
    "mountain-fold",
    "Doğu Karadeniz'in yüksek, kıyıya paralel ve buzullaşmış sırasıdır.",
    66,
    19,
    { x: -18, y: -28 },
    { image: "/images/sets/kackar.jpg", symbolScale: 1.12 },
  ),
  mountain(
    "karcal-daglari",
    "Karçal Dağları",
    8,
    "mountain-fold",
    "Artvin'in kuzeydoğusunda Gürcistan sınırına yakın yükselir.",
    77,
    8,
    { x: 18, y: -22 },
    { symbolScale: 0.86 },
  ),
  mountain(
    "yalnizcam-daglari",
    "Yalnızçam Dağları",
    75,
    "mountain-fold",
    "Artvin ile Ardahan arasında kuzeydoğu-güneybatı doğrultusunda uzanır.",
    81,
    17,
    { x: 10, y: -24 },
    { symbolScale: 0.9 },
  ),
  mountain(
    "allahuekber-daglari",
    "Allahuekber Dağları",
    36,
    "mountain-fold",
    "Kars ile Erzurum arasında uzanan yüksek dağ sırasıdır.",
    85,
    18,
    { x: 22, y: -24 },
    { symbolScale: 0.9 },
  ),
  mountain(
    "madra-dagi",
    "Madra Dağı",
    10,
    "mountain-fault-block",
    "Bakırçay ile Edremit çevresindeki çöküntü alanları arasında kalan horsttur.",
    5,
    50,
    { x: 0, y: -30 },
    { symbolScale: 0.78 },
  ),
  mountain(
    "yunt-dagi",
    "Yunt Dağı",
    45,
    "mountain-fault-block",
    "Bakırçay ve Gediz grabenleri arasında yükselen Ege horstudur.",
    6,
    61,
    { x: -12, y: -20 },
    { symbolScale: 0.8 },
  ),
  mountain(
    "bozdaglar",
    "Bozdağlar",
    35,
    "mountain-fault-block",
    "Gediz ile Küçük Menderes grabenleri arasında doğu-batı uzanır.",
    9,
    68,
    { x: 0, y: -20 },
    { symbolScale: 1.02 },
  ),
  mountain(
    "aydin-daglari",
    "Aydın Dağları",
    9,
    "mountain-fault-block",
    "Küçük ve Büyük Menderes grabenleri arasında uzanan horsttur.",
    8,
    77,
    { x: -12, y: -19 },
    { symbolScale: 0.9 },
  ),
  mountain(
    "mentese-daglari",
    "Menteşe Dağları",
    48,
    "mountain-fault-block",
    "Güneybatı Anadolu'da faylarla parçalanmış dağlık kütledir.",
    7,
    85,
    { x: -18, y: 20 },
    { symbolScale: 1.06 },
  ),
  mountain(
    "egrigoz-dagi",
    "Eğrigöz Dağı",
    43,
    "mountain-fold",
    "Kütahya'nın batısında İç Batı Anadolu eşiğinde yükselir.",
    11,
    41,
    { x: -18, y: 18 },
    { symbolScale: 0.78 },
  ),
  mountain(
    "turkmen-dagi",
    "Türkmen Dağı",
    43,
    "mountain-fold",
    "Kütahya ile Eskişehir arasındaki dağlık kuşakta yer alır.",
    15,
    43,
    { x: -18, y: -18 },
    { symbolScale: 0.78 },
  ),
  mountain(
    "murat-dagi",
    "Murat Dağı",
    64,
    "mountain-fold",
    "Uşak ile Kütahya arasında İç Batı Anadolu'da yükselir.",
    13,
    52,
    { x: 18, y: -20 },
    { symbolScale: 0.8 },
  ),
  mountain(
    "kula-volkanlari",
    "Kula Volkanları",
    45,
    "mountain-volcanic",
    "Manisa'nın Kula çevresindeki genç volkan konileri ve lav alanlarıdır.",
    14,
    61,
    { x: -4, y: 24 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "sundiken-daglari",
    "Sündiken Dağları",
    26,
    "mountain-fold",
    "Eskişehir'in kuzeyinde Sakarya havzasına paralel uzanır.",
    22,
    46,
    { x: 0, y: 18 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "emirdag",
    "Emirdağ",
    3,
    "mountain-fold",
    "Afyonkarahisar'ın doğusunda İç Batı Anadolu ile İç Anadolu arasında yükselir.",
    21,
    57,
    { x: 0, y: -19 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "sivrihisar-daglari",
    "Sivrihisar Dağları",
    26,
    "mountain-fold",
    "Eskişehir'in güneydoğusunda İç Anadolu'nun batı kenarında yer alır.",
    26,
    54,
    { x: 18, y: 20 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "elmadag",
    "Elmadağ",
    6,
    "mountain-fold",
    "Ankara'nın doğusunda İç Anadolu platosu üzerinde yükselir.",
    32,
    46,
    { x: 22, y: 42 },
    { symbolScale: 0.78 },
  ),
  mountain(
    "sandikli-daglari",
    "Sandıklı Dağları",
    3,
    "mountain-fold",
    "Afyonkarahisar'ın güneyinde İç Batı Anadolu'da uzanır.",
    18,
    69,
    { x: -18, y: 22 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "honaz-dagi",
    "Honaz Dağı",
    20,
    "mountain-fold",
    "Denizli'nin güneydoğusunda Batı Anadolu'nun yüksek kütlelerinden biridir.",
    14,
    75,
    { x: -18, y: 18 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "golgeli-daglari",
    "Gölgeli Dağları",
    20,
    "mountain-fold",
    "Denizli'nin güneyinde Batı Toroslar'a yaklaşan dağ sırasıdır.",
    11,
    88,
    { x: -20, y: 18 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "akdaglar",
    "Akdağlar",
    48,
    "mountain-fold",
    "Muğla ile Antalya arasında Batı Toroslar'ın batı ucunda uzanır.",
    15,
    91,
    { x: -18, y: 20 },
    { symbolScale: 0.88 },
  ),
  mountain(
    "beydaglari",
    "Beydağları",
    7,
    "mountain-fold",
    "Antalya Körfezi'nin batısında Batı Toroslar'ın yüksek bölümüdür.",
    17,
    97,
    { x: 20, y: 18 },
    { symbolScale: 0.9 },
  ),
  mountain(
    "katrancik-daglari",
    "Katrancık Dağları",
    15,
    "mountain-fold",
    "Burdur ile Antalya arasındaki Batı Toros kuşağında yer alır.",
    19,
    87,
    { x: 0, y: 22 },
    { symbolScale: 0.85 },
  ),
  mountain(
    "sultan-daglari",
    "Sultan Dağları",
    3,
    "mountain-fold",
    "Afyonkarahisar ile Konya arasında kuzeybatı-güneydoğu uzanır.",
    22,
    69,
    { x: 18, y: 18 },
    { symbolScale: 0.92 },
  ),
  mountain(
    "barla-dagi",
    "Barla Dağı",
    32,
    "mountain-fold",
    "Isparta'nın kuzeyinde Eğirdir Gölü çevresinde yükselir.",
    24,
    76,
    { x: -18, y: -32 },
    { symbolScale: 0.88 },
  ),
  mountain(
    "dedegol-geyik-daglari",
    "Dedegöl–Geyik Dağları",
    32,
    "mountain-fold",
    "Isparta'dan Antalya ve Konya yönüne uzanan Batı Toros sıralarıdır.",
    30,
    86,
    { x: -12, y: 22 },
    { symbolScale: 1.05 },
  ),
  mountain(
    "hinzir-dagi",
    "Hınzır Dağı",
    38,
    "mountain-fold",
    "Kayseri'nin kuzeydoğusunda İç Anadolu'nun doğu kesiminde yükselir.",
    41,
    51,
    { x: 0, y: -19 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "erciyes-dagi",
    "Erciyes Dağı",
    38,
    "mountain-volcanic",
    "Kayseri'nin güneyinde İç Anadolu'nun en yüksek volkanik kütlesidir.",
    41,
    61,
    { x: 0, y: -25 },
    { image: "/images/sets/erciyes.jpg", symbolScale: 0.9 },
  ),
  mountain(
    "hasan-dagi",
    "Hasan Dağı",
    68,
    "mountain-volcanic",
    "Aksaray ile Niğde arasında yükselen büyük volkan konisidir.",
    35,
    70,
    { x: -9, y: -24 },
    { symbolScale: 0.84 },
  ),
  mountain(
    "melendiz-daglari",
    "Melendiz Dağları",
    51,
    "mountain-volcanic",
    "Niğde çevresinde geniş bir volkanik kütle oluşturur.",
    41,
    70,
    { x: 8, y: -24 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "karacadag-ic-anadolu",
    "Karacadağ",
    42,
    "mountain-volcanic",
    "Konya çevresinde İç Anadolu volkanik alanı içinde yer alır.",
    35,
    81,
    { x: 18, y: -12 },
    { symbolScale: 0.78 },
  ),
  mountain(
    "karadag",
    "Karadağ",
    70,
    "mountain-volcanic",
    "Karaman'ın kuzeyinde sönmüş bir volkanik kütledir.",
    32,
    84,
    { x: -23, y: 18 },
    { symbolScale: 0.8 },
  ),
  mountain(
    "bolkar-daglari",
    "Bolkar Dağları",
    33,
    "mountain-fold",
    "Mersin ile Niğde arasında Orta Toroslar'ın batı bölümünü oluşturur.",
    33,
    90,
    { x: -4, y: 21 },
    { symbolScale: 0.94 },
  ),
  mountain(
    "aladaglar",
    "Aladağlar",
    51,
    "mountain-fold",
    "Niğde, Kayseri ve Adana arasında Orta Toroslar'ın yüksek bölümüdür.",
    40,
    81,
    { x: 12, y: 18 },
    { symbolScale: 0.98 },
  ),
  mountain(
    "tahtali-daglari",
    "Tahtalı Dağları",
    38,
    "mountain-fold",
    "Kayseri'nin doğusundan Kahramanmaraş yönüne uzanan sıradır.",
    46,
    70,
    { x: 0, y: -21 },
    { symbolScale: 0.84 },
  ),
  mountain(
    "binboga-daglari",
    "Binboğa Dağları",
    46,
    "mountain-fold",
    "Kahramanmaraş'ın kuzeyinde Doğu Toros kuşağında uzanır.",
    51,
    80,
    { x: 0, y: 20 },
    { symbolScale: 0.9 },
  ),
  mountain(
    "tecer-daglari",
    "Tecer Dağları",
    58,
    "mountain-fold",
    "Sivas'ın güneydoğusunda İç Anadolu ile Doğu Anadolu arasında yükselir.",
    52,
    55,
    { x: -4, y: -20 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "malatya-daglari",
    "Malatya Dağları",
    44,
    "mountain-fold",
    "Malatya'nın güneyinde Doğu ve Güneydoğu Toros kuşaklarını bağlar.",
    60,
    69,
    { x: 0, y: -20 },
    { symbolScale: 0.92 },
  ),
  mountain(
    "munzur-mercan-daglari",
    "Munzur–Mercan Dağları",
    62,
    "mountain-fold",
    "Tunceli ile Erzincan arasında yüksek ve engebeli bir sıra oluşturur.",
    60,
    52,
    { x: 18, y: 24 },
    { symbolScale: 0.98 },
  ),
  mountain(
    "cimen-daglari",
    "Çimen Dağları",
    24,
    "mountain-fold",
    "Erzincan'ın kuzeyinde Doğu Karadeniz'in iç sıralarında uzanır.",
    60,
    34,
    { x: -8, y: -21 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "kop-daglari",
    "Kop Dağları",
    69,
    "mountain-fold",
    "Bayburt ile Erzurum arasında geçit veren dağlık kuşaktır.",
    68,
    31,
    { x: 0, y: -20 },
    { symbolScale: 0.82 },
  ),
  mountain(
    "karasu-aras-daglari",
    "Karasu–Aras Dağları",
    25,
    "mountain-fold",
    "Erzurum çevresinde Karasu ve Aras havzalarını ayıran sıradır.",
    67,
    47,
    { x: 18, y: -20 },
    { symbolScale: 0.92 },
  ),
  mountain(
    "mescit-daglari",
    "Mescit Dağları",
    25,
    "mountain-fold",
    "Erzurum'un kuzeyinde Çoruh ve Aras havzaları arasında yükselir.",
    76,
    28,
    { x: -18, y: 20 },
    { symbolScale: 0.84 },
  ),
  mountain(
    "palandoken-daglari",
    "Palandöken Dağları",
    25,
    "mountain-fold",
    "Erzurum kentinin güneyinde kuzeydoğu-güneybatı doğrultusunda uzanır.",
    76,
    44,
    { x: -18, y: 20 },
    { symbolScale: 0.9 },
  ),
  mountain(
    "aras-daglari",
    "Aras Dağları",
    76,
    "mountain-fold",
    "Aras Vadisi'nin güneyinde Ağrı ve Iğdır yönünde uzanır.",
    84,
    48,
    { x: -20, y: 18 },
    { symbolScale: 0.92 },
  ),
  mountain(
    "guneydogu-toroslar",
    "Güneydoğu Toroslar",
    21,
    "mountain-fold",
    "Malatya'dan Hakkâri yönüne uzanan Toros sisteminin güneydoğu koludur.",
    72,
    66,
    { x: -8, y: -23 },
    { symbolScale: 1.18 },
  ),
  mountain(
    "amanos-daglari",
    "Amanos Dağları",
    31,
    "mountain-fault-block",
    "İskenderun Körfezi'nin doğusunda kuzey-güney uzanan Nur Dağlarıdır.",
    51,
    97,
    { x: -22, y: -25 },
    { labelRotation: -62, symbolScale: 0.94 },
  ),
  mountain(
    "karacadag-guneydogu",
    "Karacadağ",
    21,
    "mountain-volcanic",
    "Diyarbakır ile Şanlıurfa arasında geniş tabanlı bir kalkan volkandır.",
    69,
    79,
    { x: -20, y: -22 },
    { symbolScale: 0.86 },
  ),
  mountain(
    "mardin-daglari",
    "Mardin Dağları",
    47,
    "mountain-fold",
    "Mardin eşiği boyunca Güneydoğu Anadolu'nun güneyinde uzanır.",
    78,
    86,
    { x: -8, y: -22 },
    { symbolScale: 0.88 },
  ),
  mountain(
    "nemrut-dagi",
    "Nemrut Dağı",
    13,
    "mountain-volcanic",
    "Van Gölü'nün batısında kalderası ve kaldera gölüyle tanınır.",
    81,
    56,
    { x: -18, y: 22 },
    { symbolScale: 0.84 },
  ),
  mountain(
    "suphan-dagi",
    "Süphan Dağı",
    13,
    "mountain-volcanic",
    "Van Gölü'nün kuzeyinde yükselen sönmüş volkan konisidir.",
    86,
    46,
    { x: -18, y: -22 },
    { symbolScale: 0.86 },
  ),
  mountain(
    "tendurek-dagi",
    "Tendürek Dağı",
    4,
    "mountain-volcanic",
    "Ağrı ile Van arasında yer alan geniş volkanik kütledir.",
    90,
    43,
    { x: 18, y: 22 },
    { symbolScale: 0.84 },
  ),
  mountain(
    "buyuk-agri-dagi",
    "Büyük Ağrı Dağı",
    4,
    "mountain-volcanic",
    "Türkiye'nin en yüksek noktası olan büyük stratovolkan konisidir.",
    95,
    31,
    { x: 18, y: -24 },
    { image: "/images/sets/agri-dagi.jpg", symbolScale: 0.76 },
  ),
  mountain(
    "kucuk-agri-dagi",
    "Küçük Ağrı Dağı",
    4,
    "mountain-volcanic",
    "Büyük Ağrı'nın güneydoğusunda yükselen daha küçük volkan konisidir.",
    93,
    37,
    { x: 0, y: 62 },
    { symbolScale: 0.78 },
  ),
  mountain(
    "ihtiyar-sahap-daglari",
    "İhtiyar Şahap Dağları",
    65,
    "mountain-fold",
    "Van Gölü'nün güneyinde doğu-batı doğrultusunda uzanan sıradır.",
    84,
    69,
    { x: -24, y: 20 },
    { symbolScale: 0.9 },
  ),
  mountain(
    "hakkari-daglari",
    "Hakkâri Dağları",
    30,
    "mountain-fold",
    "Türkiye'nin güneydoğusunda çok yüksek ve engebeli sıralar oluşturur.",
    87,
    80,
    { x: -8, y: -22 },
    { symbolScale: 0.96 },
  ),
  mountain(
    "buzul-daglari",
    "Buzul Dağları",
    30,
    "mountain-fold",
    "Hakkâri'nin doğusunda güncel buzul izlerinin görüldüğü yüksek kütledir.",
    93,
    77,
    { x: 20, y: 24 },
    { symbolScale: 0.9 },
  ),
];

export const MOUNTAIN_ATLAS_ENTRIES: MountainAtlasEntry[] =
  MOUNTAIN_ATLAS_SEEDS.map(({ layout: _layout, ...entry }) => entry);

export const MOUNTAIN_ATLAS_LAYOUTS: Record<string, MountainAtlasLayout> =
  Object.fromEntries(
    MOUNTAIN_ATLAS_SEEDS.map(({ id, layout }) => [id, layout]),
  );
