export type ReadyQuizQuestion = {
  id: string;
  prompt: string;
  choices: string[];
  correctAnswer: string;
  explanation: string;
};

export const QUIZ_BANKS: Record<string, ReadyQuizQuestion[]> = {
  mountains: [
    {
      id: "mountain-highest",
      prompt: "Türkiye'nin en yüksek dağı hangisidir?",
      choices: ["Ağrı Dağı", "Erciyes Dağı", "Kaçkar Dağları", "Süphan Dağı"],
      correctAnswer: "Ağrı Dağı",
      explanation: "Ağrı Dağı 5.137 metreyle Türkiye'nin en yüksek dağıdır.",
    },
    {
      id: "mountain-fold-system",
      prompt: "Kuzey Anadolu Dağları ve Toroslar hangi oluşum grubundadır?",
      choices: ["Kıvrım dağları", "Kırık dağlar", "Volkanik dağlar", "Aşınım dağları"],
      correctAnswer: "Kıvrım dağları",
      explanation: "Bu iki sistem Alp-Himalaya kuşağındaki genç kıvrım dağlarıdır.",
    },
    {
      id: "mountain-horst",
      prompt: "Aşağıdakilerden hangisi Ege Bölgesi'ndeki kırık dağlardan biridir?",
      choices: ["Aydın Dağları", "Kaçkar Dağları", "Canik Dağları", "Bolkar Dağları"],
      correctAnswer: "Aydın Dağları",
      explanation: "Aydın Dağları, Ege'de grabenler arasında yükselen bir horsttur.",
    },
    {
      id: "mountain-volcanic",
      prompt: "Aşağıdakilerden hangisi volkanik dağdır?",
      choices: ["Erciyes", "Ilgaz", "Küre", "Amanos"],
      correctAnswer: "Erciyes",
      explanation: "Erciyes, İç Anadolu'nun en yüksek volkanik dağıdır.",
    },
    {
      id: "mountain-kackar",
      prompt: "Kaçkar Dağları hangi dağ sisteminin yüksek bölümündedir?",
      choices: ["Doğu Karadeniz Dağları", "Batı Toroslar", "Ege horstları", "Yıldız Dağları"],
      correctAnswer: "Doğu Karadeniz Dağları",
      explanation: "Kaçkarlar, Doğu Karadeniz Dağları'nın en yüksek bölümünü oluşturur.",
    },
    {
      id: "mountain-karacadag",
      prompt: "Diyarbakır-Şanlıurfa arasında bulunan kalkan volkan hangisidir?",
      choices: ["Karacadağ", "Nemrut", "Melendiz", "Tendürek"],
      correctAnswer: "Karacadağ",
      explanation: "Karacadağ geniş tabanlı bir kalkan volkandır.",
    },
    {
      id: "mountain-nemrut",
      prompt: "Kalderası ve kaldera gölüyle tanınan volkanik dağ hangisidir?",
      choices: ["Nemrut", "Hasan", "Karadağ", "Süphan"],
      correctAnswer: "Nemrut",
      explanation: "Bitlis'teki Nemrut Dağı geniş kalderasıyla tanınır.",
    },
    {
      id: "mountain-amonos",
      prompt: "Nur Dağları adıyla da bilinen dağ sırası hangisidir?",
      choices: ["Amanos Dağları", "Geyik Dağları", "Sultan Dağları", "Mercan Dağları"],
      correctAnswer: "Amanos Dağları",
      explanation: "Amanos Dağları, İskenderun Körfezi'nin doğusunda uzanır.",
    },
  ],
  lakes: [
    {
      id: "lake-largest",
      prompt: "Türkiye'nin yüz ölçümü bakımından en büyük gölü hangisidir?",
      choices: ["Van Gölü", "Tuz Gölü", "Beyşehir Gölü", "Eğirdir Gölü"],
      correctAnswer: "Van Gölü",
      explanation: "Van Gölü Türkiye'nin en büyük gölüdür.",
    },
    {
      id: "lake-freshwater",
      prompt: "Türkiye'nin en büyük tatlı su gölü hangisidir?",
      choices: ["Beyşehir Gölü", "Van Gölü", "Tuz Gölü", "Burdur Gölü"],
      correctAnswer: "Beyşehir Gölü",
      explanation: "Beyşehir, Türkiye'nin en büyük tatlı su gölüdür.",
    },
    {
      id: "lake-van-origin",
      prompt: "Van Gölü'nün oluşumu nasıl sınıflandırılır?",
      choices: ["Tektonik-volkanik set", "Karstik", "Buzul", "Kıyı set"],
      correctAnswer: "Tektonik-volkanik set",
      explanation: "Tektonik çanakta Nemrut volkanının oluşturduğu set de etkili olmuştur.",
    },
    {
      id: "lake-tortum",
      prompt: "Tortum Gölü hangi doğal olay sonucu oluşmuştur?",
      choices: ["Heyelan seti", "Volkanik krater", "Buzul aşındırması", "Kıyı oku"],
      correctAnswer: "Heyelan seti",
      explanation: "Heyelan kütlesi Tortum Çayı vadisini kapatmıştır.",
    },
    {
      id: "lake-meke",
      prompt: "Meke Gölü hangi kökene sahiptir?",
      choices: ["Volkanik", "Tektonik", "Buzul", "Baraj"],
      correctAnswer: "Volkanik",
      explanation: "Meke, Karapınar'da bir maar içinde gelişmiş volkanik göldür.",
    },
    {
      id: "lake-salda",
      prompt: "Salda Gölü hangi oluşum grubunda değerlendirilir?",
      choices: ["Karstik", "Tektonik", "Volkanik set", "Buzul"],
      correctAnswer: "Karstik",
      explanation: "Salda, karstik çanakta bulunan kapalı havza gölüdür.",
    },
    {
      id: "lake-artificial",
      prompt: "Aşağıdakilerden hangisi yapay göldür?",
      choices: ["Atatürk Baraj Gölü", "Sapanca Gölü", "İznik Gölü", "Manyas Gölü"],
      correctAnswer: "Atatürk Baraj Gölü",
      explanation: "Atatürk Baraj Gölü, Fırat üzerindeki barajla oluşturulmuştur.",
    },
    {
      id: "lake-mixed",
      prompt: "Beyşehir ve Eğirdir göllerinin ortak oluşum özelliği nedir?",
      choices: ["Tektonik-karstik", "Volkanik", "Heyelan seti", "Buzul"],
      correctAnswer: "Tektonik-karstik",
      explanation: "Her iki gölde tektonik ve karstik süreçler birlikte etkilidir.",
    },
  ],
  rivers: [
    {
      id: "river-longest",
      prompt: "Tamamı Türkiye sınırları içindeki en uzun akarsu hangisidir?",
      choices: ["Kızılırmak", "Fırat", "Sakarya", "Yeşilırmak"],
      correctAnswer: "Kızılırmak",
      explanation: "Kızılırmak, ülke sınırları içindeki en uzun akarsudur.",
    },
    {
      id: "river-asi",
      prompt: "Suriye'den Türkiye'ye ulaşıp Hatay'dan Akdeniz'e dökülen nehir hangisidir?",
      choices: ["Asi", "Çoruh", "Aras", "Ceyhan"],
      correctAnswer: "Asi",
      explanation: "Asi Lübnan'dan doğar, Suriye üzerinden Hatay'a ulaşır.",
    },
    {
      id: "river-coruh",
      prompt: "Türkiye'den doğup Gürcistan'da Karadeniz'e dökülen akarsu hangisidir?",
      choices: ["Çoruh", "Meriç", "Dicle", "Sakarya"],
      correctAnswer: "Çoruh",
      explanation: "Çoruh Türkiye'den doğar ve Gürcistan sınırlarında denize ulaşır.",
    },
    {
      id: "river-firat-branches",
      prompt: "Fırat Nehri hangi iki ana ırmağın birleşmesiyle oluşur?",
      choices: ["Karasu ve Murat", "Kelkit ve Çekerek", "Zamantı ve Göksu", "Batman ve Botan"],
      correctAnswer: "Karasu ve Murat",
      explanation: "Fırat, Karasu ile Murat ırmaklarının birleşmesiyle oluşur.",
    },
    {
      id: "river-basra",
      prompt: "Fırat ve Dicle ülke dışında birleşerek hangi körfeze ulaşır?",
      choices: ["Basra Körfezi", "İskenderun Körfezi", "İzmir Körfezi", "Saros Körfezi"],
      correctAnswer: "Basra Körfezi",
      explanation: "İki nehir Şattülarap'ı oluşturup Basra Körfezi'ne dökülür.",
    },
    {
      id: "river-delta",
      prompt: "Seyhan ve Ceyhan nehirleri hangi deltayı oluşturur?",
      choices: ["Çukurova", "Bafra", "Çarşamba", "Gediz"],
      correctAnswer: "Çukurova",
      explanation: "Seyhan ve Ceyhan, Çukurova Deltası'nın oluşumunda etkilidir.",
    },
    {
      id: "river-transport",
      prompt: "Bazı kesimlerinde kısmen ulaşım yapılabilen akarsu hangisidir?",
      choices: ["Bartın Çayı", "Kızılırmak", "Büyük Menderes", "Fırat"],
      correctAnswer: "Bartın Çayı",
      explanation: "Bartın Çayı'nın bazı bölümleri ulaşım için elverişlidir.",
    },
    {
      id: "river-meric",
      prompt: "Bulgaristan'dan doğup Türkiye-Yunanistan sınırının bir bölümünü izleyen nehir hangisidir?",
      choices: ["Meriç", "Aras", "Asi", "Gediz"],
      correctAnswer: "Meriç",
      explanation: "Meriç, Bulgaristan'dan gelir ve sınırın bir bölümünü oluşturur.",
    },
  ],
  agriculture: [
    {
      id: "agri-wheat",
      prompt: "MEB'e göre buğday üretiminde öne çıkan üç il hangileridir?",
      choices: ["Konya-Ankara-Diyarbakır", "Konya-Yozgat-Aksaray", "Adana-Mersin-Samsun", "Manisa-Aydın-Bursa"],
      correctAnswer: "Konya-Ankara-Diyarbakır",
      explanation: "MEB konu özetinde buğday için Konya, Ankara ve Diyarbakır verilir.",
    },
    {
      id: "agri-rice",
      prompt: "Çeltik üretiminde öne çıkan iller hangileridir?",
      choices: ["Edirne-Samsun-Balıkesir", "Rize-Artvin-Trabzon", "Konya-Ankara-Şanlıurfa", "Gaziantep-Şanlıurfa-Mardin"],
      correctAnswer: "Edirne-Samsun-Balıkesir",
      explanation: "Çeltik bol su ister; MEB bu üç ili ana merkez olarak verir.",
    },
    {
      id: "agri-soy",
      prompt: "Soya fasulyesi üretiminde öne çıkan iller hangileridir?",
      choices: ["Adana-Mersin-Samsun", "Ordu-Giresun-Sakarya", "Manisa-Denizli-Mersin", "Konya-Niğde-Aksaray"],
      correctAnswer: "Adana-Mersin-Samsun",
      explanation: "Soya bol su ister ve bu üç il üretimde öne çıkar.",
    },
    {
      id: "agri-tea",
      prompt: "Çayın Türkiye'de yalnız Doğu Karadeniz'de yetişmesinin temel nedeni nedir?",
      choices: ["Bol yağış ve kireçsiz toprak", "Yaz kuraklığı", "Şiddetli donlar", "Tuzlu toprak"],
      correctAnswer: "Bol yağış ve kireçsiz toprak",
      explanation: "Çay özel nem ve toprak koşulları ister.",
    },
    {
      id: "agri-sugar",
      prompt: "Şeker fabrikalarının pancar tarlalarına yakın kurulmasının nedeni nedir?",
      choices: ["Pancarın sökümden sonra hemen işlenmesi", "Ürünün deniz yoluyla taşınması", "Yalnız kıyıda yetişmesi", "Soğuk hava deposu gerektirmemesi"],
      correctAnswer: "Pancarın sökümden sonra hemen işlenmesi",
      explanation: "Şeker pancarı bekletilmeden işlenmelidir.",
    },
    {
      id: "agri-microclimate",
      prompt: "Iğdır'da pamuk yetiştirilebilmesi hangi kavramla açıklanır?",
      choices: ["Mikroklima", "Karstlaşma", "Yükselti artışı", "Denizellik"],
      correctAnswer: "Mikroklima",
      explanation: "MEB, Iğdır'daki pamuk üretimini mikroklima örneği olarak verir.",
    },
    {
      id: "agri-sunflower",
      prompt: "Türkiye'nin başlıca yağ bitkisi hangisidir?",
      choices: ["Ayçiçeği", "Çay", "Tütün", "Şeker pancarı"],
      correctAnswer: "Ayçiçeği",
      explanation: "Ayçiçeği yağlı tohumlarda ekim alanı ve üretimde ilk sıradadır.",
    },
    {
      id: "agri-permit",
      prompt: "Aşağıdakilerden hangisinin ekimi belirli yerlerde devlet iznine bağlıdır?",
      choices: ["Tütün", "Buğday", "Arpa", "Fındık"],
      correctAnswer: "Tütün",
      explanation: "Tütün, haşhaş, kenevir ve çeltik izinle yetiştirilen ürünler arasındadır.",
    },
  ],
  resources: [
    {
      id: "resource-copper",
      prompt: "Aşağıdakilerden hangisi MEB'in verdiği başlıca bakır sahalarından biri değildir?",
      choices: ["Seydişehir", "Murgul", "Çayeli", "Küre"],
      correctAnswer: "Seydişehir",
      explanation: "Seydişehir boksit ve alüminyumla; diğerleri bakırla ilişkilidir.",
    },
    {
      id: "resource-coal",
      prompt: "Türkiye'nin taşkömürü havzası hangi kuşaktadır?",
      choices: ["Ereğli-Zonguldak-Amasra", "Soma-Yatağan-Elbistan", "Batman-Adıyaman-Siirt", "Kırka-Emet-Bigadiç"],
      correctAnswer: "Ereğli-Zonguldak-Amasra",
      explanation: "MEB taşkömürü yataklarını bu havzada gösterir.",
    },
    {
      id: "resource-lignite",
      prompt: "Soma, Tunçbilek ve Yatağan hangi enerji kaynağıyla ilişkilidir?",
      choices: ["Linyit", "Taşkömürü", "Petrol", "Doğal gaz"],
      correctAnswer: "Linyit",
      explanation: "Bu merkezler önemli linyit sahaları ve termik santral alanlarıdır.",
    },
    {
      id: "resource-oil-refinery",
      prompt: "Yalnız Türkiye'de çıkarılan petrolü işlediği belirtilen rafineri hangisidir?",
      choices: ["Batman Rafinerisi", "İzmit Rafinerisi", "Aliağa Rafinerisi", "Kırıkkale Rafinerisi"],
      correctAnswer: "Batman Rafinerisi",
      explanation: "MEB, Batman Rafinerisi için bu ayırt edici bilgiyi verir.",
    },
    {
      id: "resource-boron",
      prompt: "Kırka, Bigadiç, Kestelek ve Emet hangi madenle ilişkilidir?",
      choices: ["Bor", "Demir", "Krom", "Fosfat"],
      correctAnswer: "Bor",
      explanation: "Bu dört merkez Türkiye'nin başlıca bor sahalarıdır.",
    },
    {
      id: "resource-bauxite",
      prompt: "Seydişehir Alüminyum Tesislerinin temel ham maddesi hangisidir?",
      choices: ["Boksit", "Bakır", "Krom", "Fosfat"],
      correctAnswer: "Boksit",
      explanation: "Boksit alüminyumun ham maddesidir.",
    },
    {
      id: "resource-wind",
      prompt: "Rüzgâr enerjisinin özellikle yoğunlaştığı iki kıyı bölgesi hangisidir?",
      choices: ["Ege ve Marmara", "Doğu ve Güneydoğu Anadolu", "İç Anadolu ve Akdeniz", "Karadeniz ve İç Anadolu"],
      correctAnswer: "Ege ve Marmara",
      explanation: "Balıkesir, İzmir, Manisa ve Çanakkale öne çıkan merkezlerdendir.",
    },
    {
      id: "resource-gold",
      prompt: "Cumhuriyet döneminde resmî altın üretiminin başladığı ilk maden hangisidir?",
      choices: ["Bergama-Ovacık", "İliç-Çöpler", "Kışladağ", "Kaymaz"],
      correctAnswer: "Bergama-Ovacık",
      explanation: "Resmî üretim 2001'de İzmir-Bergama Ovacık'ta başlamıştır.",
    },
  ],
  trade: [
    {
      id: "trade-hinterland",
      prompt: "Bir limanın gerisindeki üretim ve ulaşım alanına ne ad verilir?",
      choices: ["Hinterland", "Mikroklima", "Graben", "Rezerv"],
      correctAnswer: "Hinterland",
      explanation: "Liman gelişiminde kıyı yapısı kadar hinterland da önemlidir.",
    },
    {
      id: "trade-europe",
      prompt: "Avrupa yönündeki kara ve demir yolu ticaretinde öne çıkan sınır kapısı hangisidir?",
      choices: ["Kapıkule", "Habur", "Gürbulak", "Cilvegözü"],
      correctAnswer: "Kapıkule",
      explanation: "Kapıkule, Edirne üzerinden Avrupa bağlantısını sağlar.",
    },
    {
      id: "trade-iraq",
      prompt: "Irak yönündeki kara yolu ticaretinin başlıca sınır kapısı hangisidir?",
      choices: ["Habur", "Kapıkule", "Gürbulak", "Sarp"],
      correctAnswer: "Habur",
      explanation: "Habur, Şırnak üzerinden Irak bağlantısında öne çıkar.",
    },
    {
      id: "trade-iran",
      prompt: "İran ve Orta Asya yönündeki kara yolu ticaretinde hangi kapı önemlidir?",
      choices: ["Gürbulak", "Cilvegözü", "Kapıkule", "Habur"],
      correctAnswer: "Gürbulak",
      explanation: "Gürbulak Ağrı'da, İran sınırındadır.",
    },
    {
      id: "trade-aegean-port",
      prompt: "Ege'nin tarım ve sanayi hinterlandını dış pazarlara bağlayan liman hangisidir?",
      choices: ["İzmir Limanı", "Samsun Limanı", "Trabzon Limanı", "Derince Limanı"],
      correctAnswer: "İzmir Limanı",
      explanation: "İzmir Limanı geniş Ege hinterlandına hizmet verir.",
    },
    {
      id: "trade-cukurova",
      prompt: "Çukurova ve Güneydoğu Anadolu'nun dış ticaret kapılarından biri hangisidir?",
      choices: ["Mersin Limanı", "Bandırma Limanı", "Trabzon Limanı", "Derince Limanı"],
      correctAnswer: "Mersin Limanı",
      explanation: "Mersin geniş bir güney ve güneydoğu hinterlandına sahiptir.",
    },
    {
      id: "trade-straits",
      prompt: "Karadeniz'i Akdeniz'e bağlayan stratejik su yolu sistemini hangisi oluşturur?",
      choices: ["İstanbul ve Çanakkale boğazları", "Süveyş ve Panama kanalları", "Hürmüz ve Babülmendep", "Korint ve Kiel kanalları"],
      correctAnswer: "İstanbul ve Çanakkale boğazları",
      explanation: "Türk Boğazları Karadeniz-Akdeniz bağlantısının merkezindedir.",
    },
    {
      id: "trade-black-sea",
      prompt: "Orta Karadeniz'in İç Anadolu bağlantılı önemli limanı hangisidir?",
      choices: ["Samsun", "Trabzon", "İskenderun", "Bandırma"],
      correctAnswer: "Samsun",
      explanation: "Samsun Limanı Orta Karadeniz ve İç Anadolu hinterlandına hizmet eder.",
    },
  ],
  industry: [
    {
      id: "industry-factors",
      prompt: "Aşağıdakilerden hangisi sanayinin kuruluş yerini etkileyen temel faktörlerden biri değildir?",
      choices: ["Gelgit genliği", "Ham madde", "Ulaşım", "Pazar"],
      correctAnswer: "Gelgit genliği",
      explanation: "Temel faktörler ham madde, enerji, sermaye, iş gücü, ulaşım ve pazardır.",
    },
    {
      id: "industry-steel",
      prompt: "Türkiye'nin başlıca demir-çelik merkezleri hangileridir?",
      choices: ["Karabük-Ereğli-İskenderun", "Bursa-Manisa-İzmir", "Rize-Artvin-Trabzon", "Konya-Yozgat-Aksaray"],
      correctAnswer: "Karabük-Ereğli-İskenderun",
      explanation: "Bu üç merkez ağır sanayinin başlıca demir-çelik alanlarıdır.",
    },
    {
      id: "industry-automotive",
      prompt: "Otomotiv sanayisinin en yoğun olduğu bölge hangisidir?",
      choices: ["Marmara", "Doğu Anadolu", "Karadeniz", "Güneydoğu Anadolu"],
      correctAnswer: "Marmara",
      explanation: "Bursa, Kocaeli, Sakarya ve İstanbul otomotivde öne çıkar.",
    },
    {
      id: "industry-refinery",
      prompt: "Aşağıdakilerden hangisi petrol rafinerisi bulunan merkezlerden biri değildir?",
      choices: ["Rize", "İzmit", "Aliağa", "Batman"],
      correctAnswer: "Rize",
      explanation: "Başlıca rafineriler İzmit, Aliağa, Kırıkkale ve Batman'dadır.",
    },
    {
      id: "industry-shipyard",
      prompt: "Gölcük, Tuzla, Pendik ve Haliç hangi sanayi koluyla ilişkilidir?",
      choices: ["Gemi yapımı", "Şeker sanayisi", "Dokuma", "Çimento"],
      correctAnswer: "Gemi yapımı",
      explanation: "Bu merkezler İstanbul-İzmit arasındaki önemli tersanelerdir.",
    },
    {
      id: "industry-tea",
      prompt: "Çay fabrikalarının Doğu Karadeniz'de kurulmasının temel nedeni nedir?",
      choices: ["Ham maddeye yakınlık", "Taşkömürü", "Geniş düz alan", "İthalat limanı"],
      correctAnswer: "Ham maddeye yakınlık",
      explanation: "Çay yaprağı çabuk bozulduğu için tesisler üretim alanına yakın olmalıdır.",
    },
    {
      id: "industry-sugar",
      prompt: "Şeker sanayisinin iç bölgelerde yaygın olmasının temel nedeni nedir?",
      choices: ["Şeker pancarı üretimi", "Deniz ulaşımı", "Orman varlığı", "Petrol yatakları"],
      correctAnswer: "Şeker pancarı üretimi",
      explanation: "Fabrikalar pancarın yetiştiği alanlara yakın kurulur.",
    },
    {
      id: "industry-aluminium",
      prompt: "Seydişehir'deki önemli maden işleme tesisi hangisidir?",
      choices: ["Alüminyum tesisi", "Bakır izabe", "Demir-çelik", "Petrol rafinerisi"],
      correctAnswer: "Alüminyum tesisi",
      explanation: "Seydişehir, boksit yataklarına bağlı alüminyum tesisiyle tanınır.",
    },
  ],
};
